version: '2'
plugins:
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  eslint:
    enabled: true
    channel: 'eslint-5'
    config:
      config: .eslintrc.js
      extensions:
        - .js
        - .jsx
exclude_patterns:
  - '**/node_modules/'
  - '**/__tests__/*'
  - '**/__mocks__/*'
